#!/usr/bin/python
# -*- coding: us-ascii -*-
# vim: syntax=python
#
# Copyright 2006-2008 Noriyuki Hosaka nori@backgammon.gr.jp
#
from wsgiref.simple_server import make_server
from jsboard.move import app


httpd = make_server('', 8002, app);

httpd.serve_forever();
